
print("На какой поз нашло?")
print("введите цифру от 1 до 5")
import random
from time import sleep
import webbrowser

ac=("alchemist")
bc=("bloodseeker")
sc=("spectre")
lc=("lifestealer")
mc=("morphling")
tc=("terrorblade")
jc=("juggernaut")
hc = ("shadow fiend")
amc = ("anti-mage")
pc = ("phantom assasin")
list=([ac, bc, sc, lc, mc, tc, jc, hc, amc, pc])
#на мид нахуй
em = ("ember spirit")
mm = ("monkey king")
am = ("earthshaker")
pm = ("puck")
vm = ("void spirit")
gm = ("magnus")
lm = ("lina")
tm = ("tiny")
im = ("invoker")
list2=([em, mm, am, pm, vm, gm, lm,tm,im])
#на тройку нахуй
e3 = ("enigma")
p3 = ("pheonix")
l3 = ("lycan")
t3 = ("tidehunter")
a3 = ("earthshaker")
n3 = ("night stalker")
d3 = ("dawnbreaker")
x3 = ("axe")
g3 = ("legion commander")
o3 = ("doom")
list3=([e3,p3,l3,t3,a3,n3,d3,x3,g3,o3,])
#насемисапа
b4 = ("bounty hunter")
c4 = ("clockwerk")
s4 = ("shadow shaman")
l4 = ("lion")
z4 = ("zeus")
p4 = ("spirit breaker")
n4 = ("nyx assasin")
u4 = ("pugna")
d4 = ("shadow demon")
PUDGE = ("PUDGE")
list4=([b4,c4,s4,l4,z4,p4,n4,u4,d4,PUDGE])
#НА ФУЛЛ САПА НАХУЙ
v5 = ("venomancer")
i5 = ("io")
o5 = ("oracle")
l5 = ("lich")
s5 = ("shadow shaman")
a5 = ("abbadon")
p5 = ("pugna")
c5 = ("clockwerk")
g5 = ("ogre mage")
e5 = ("silencer")
u5 = ("undying")
d5 = ("disruptor")
list5 =([v5,i5,o5,l5,s5,a5,p5,c5,g5,e5,u5,d5])
vopros = input("[1][2][3][4][5]: ")
if vopros == ("1"):
   carry = random.choice (list)
   print("пикай "+carry)
if vopros == ("2"):
    mid = random.choice(list2)
    print("пикай "+mid)
if vopros == ("3"):
    offlane = random.choice(list3)
    print("пикай "+offlane)
if vopros == ("4"):
    semisup = random.choice(list4)
    print("пикай "+semisup)
if vopros == ("5"):
    fullsup = random.choice(list5)
    print("пикай "+fullsup)
if vopros == ("6"):
    webbrowser.open('https://www.twitch.tv/stray228?lang=ru', new=2)
    print("шо ты галава")
sleep(5)
